config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'statics#home'
  
  get '/terms_and_conditions', to: 'statics#terms_and_conditions'
  get '/privacy_policy', to: 'statics#privacy_policy'
  get '/criteria_table_info', to: 'statics#criteria_table_info'
  get '/admin', to: 'admin#admin'
  get '/admin/messages', to: 'admin#messages'
  get '/admin/switchers', to: 'admin#switchers'
  get '/admin/subscribers', to: 'admin#subscribers'
  get '/admin/faqs', to: 'admin#faqs'
  get '/admin/new_faq', to: 'admin#new_faq'
  get '/placeholder', to: 'statics#placeholder'
  post '/home_switch', to: 'statics#home_switch'
  post '/change_state', to: 'power_providers#change_state'
  
  resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :faq_tags, only: [:create, :destroy]
  resources :messages, only: [:new, :create]
  resources :partners, only: [:new, :show]
  resources :charities, only: [:show]
  resources :power_providers, only: [:index]
  resources :subscribers, only: [:create]
  
  resources :switches, only: [:new, :create, :update] do
    get 'ethical_power', on: :collection
    get 'ethical_super', on: :collection
    get 'ethical_homeloans', on: :collection
    get 'homeloans_sent', on: :collection
  end
  
  # Legacy routes
  
  #  Charity.all.each do |charity|
  #    get "#{charity.filename.gsub("_", "")}", to: redirect("/charities/#{charity.id}")
  #  end
  #  
  #  get "greenpledge", to: redirect("/charities/#{Charity.find_by(name: "The Green Pledge").id}")
  #  get "habitat", to: redirect("/charities/#{Charity.find_by(name: "Habitat for Humanity Australia").id}")
  #  get "ms", to: redirect("/charities/#{Charity.find_by(name: "MS Australia").id}")
  #  get "onemillionwomen", to: redirect("/charities/#{Charity.find_by(name: "1 Million Women").id}")
  #  get "1millionwomen", to: redirect("/charities/#{Charity.find_by(name: "1 Million Women").id}")
  
  get "ethicalpower", to: redirect("/switches/ethical_power")
  get "ethical-power", to: redirect("/switches/ethical_power")
  
  get "ethicalsuper", to: redirect("/switches/ethical_super")
  get "ethical-super", to: redirect("/switches/ethical_super")
  
  get "ethicalhomeloans", to: redirect("/switches/ethical_homeloans")
  get "ethical-homeloans", to: redirect("/switches/ethical_homeloans")
end

app/models/faq.rb
class Faq < ApplicationRecord
  has_many :faq_tags
  has_many :tags, through: :faq_tags
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  def index
    @faqs = Faq.all
  end
  
  def create
    @faq = Faq.create(faq_params)
    redirect_to admin_faqs_path, notice: "FAQ created"
  end
  
  def edit
    @faq = Faq.find(params[:id])
  end
  
  def update
    @faq = Faq.find(params[:id])
    @faq.update(faq_params)
    redirect_to admin_faqs_path, notice: "FAQ updated"
  end
  
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy
    redirect_to admin_faqs_path, notice: "FAQ deleted"
  end
  
  private
  
  def faq_params
    params.require(:faq).permit(:title, :answer)
  end
end

app/views/faqs/_faq.html.erb
<div class="faq_container">
  <div class="faq">
    <div class="faq_question lhi-sm">
      <%= image_tag "plus.png" %>
      <p class="m0 mt12-sm"><%= faq.title %></p>
    </div>

    <div class="faq_answer_container">
      <div class="faq_answer p10">
        <%= faq.answer.html_safe %>
      </div>        
    </div>
  </div>
</div>

app/views/faqs/_faq_admin.html.erb
<div class="faq_admin_<%= faq.id %>">
  <p class="fwb"><%= faq.title %> <span class="flr"><%= link_to "edit", edit_faq_path(faq), class: "fake-link" %> | <%= link_to "delete", faq_path(faq), method: :delete, class: "fake-link" %></span></p>
  <p><%= faq.answer.html_safe %></p>

  <div class="mb40">
    <span class="db fwb mb10">Show on:</span>

    <% @tags.each do |tag| %>
      <% if faq.tags.include?(tag) %>
        <%= form_for(FaqTag.find_by(faq_id: faq.id, tag_id: tag.id), method: :delete, remote: true, html: {class: "di"}) do |f| %>
          <%= hidden_field_tag :faq_id, faq.id %>
          <%= f.submit tag.name, class: "btn btn-grey mb5 btn-grey-selected" %>
        <% end %>
      <% else %>
        <%= form_for(FaqTag.new, remote: true, html: {class: "di"}) do |f| %>
          <%= f.hidden_field :faq_id, value: faq.id %>
          <%= f.hidden_field :tag_id, value: tag.id %>
          <%= f.submit tag.name, class: "btn btn-grey mb5" %>
        <% end %>
      <% end %>
    <% end %>
    
    <div class="clb"></div>
  </div>

  <hr class="mb40">
</div>

app/views/faqs/_form.html.erb
<%= form_for(@faq) do |f| %>
  <%= f.text_field :title, placeholder: "Question", class: "form-control" %>
  <%= f.text_area :answer, placeholder: "Answer", class: "form-control" %>

  <div class="tac">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<% if current_user && current_user.admin %>
  <div class="row text-page-header mb40 text-s">
    <div class="col-sm-8 col-sm-offset-2">
      <%= link_to "Dashboard", admin_path %> > <%= link_to "FAQs", admin_faqs_path %> > Edit FAQ
    </div>
    
    <div class="clb"></div>
  </div>
  
  <div class="col-sm-8 col-sm-offset-2 mb40">
    <%= render 'faqs/form' %>
  </div>
<% else %>
  <div class="tac">You are not authorized to view this page</div>
<% end %>

app/views/faqs/index.html.erb
<div class="text-page">
  <header class="row flex-center">
    <h1 class="tac">FAQs</h1>
  </header>

  <main class="faqs col-sm-8 col-sm-offset-2">
    <ul>
      <% @faqs.each do |faq| %>
        <li>
          <%= link_to faq.title, "##{faq.title.downcase.gsub(" ", "_").gsub("?", "")}" %>
        </li>
      <% end %>
    </ul>
		
    <% @faqs.each do |faq| %>
      <div class="faq">
        <h4 id="<%= "#{faq.title.downcase.gsub(" ", "_").gsub("?", "")}" %>"><%= faq.title %></h4>

        <%= faq.answer.html_safe %>

        <a href="#" class="faqs-top">^ Back to the top</a>
      </div>
    <% end %>
  </main>
  
  <div class="clb"></div>
</div>