config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'statics#home'
  
  get '/terms_and_conditions', to: 'statics#terms_and_conditions'
  get '/privacy_policy', to: 'statics#privacy_policy'
  get '/criteria_table_info', to: 'statics#criteria_table_info'
  get '/admin', to: 'admin#admin'
  get '/admin/messages', to: 'admin#messages'
  get '/admin/switchers', to: 'admin#switchers'
  get '/admin/subscribers', to: 'admin#subscribers'
  get '/admin/faqs', to: 'admin#faqs'
  get '/admin/new_faq', to: 'admin#new_faq'
  get '/placeholder', to: 'statics#placeholder'
  post '/home_switch', to: 'statics#home_switch'
  post '/change_state', to: 'power_providers#change_state'
  
  resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :faq_tags, only: [:create, :destroy]
  resources :messages, only: [:new, :create]
  resources :partners, only: [:new, :show]
  resources :charities, only: [:show]
  resources :power_providers, only: [:index]
  resources :subscribers, only: [:create]
  
  resources :switches, only: [:new, :create, :update] do
    get 'ethical_power', on: :collection
    get 'ethical_super', on: :collection
    get 'ethical_homeloans', on: :collection
    get 'homeloans_sent', on: :collection
  end
  
  # Legacy routes
  
  #  Charity.all.each do |charity|
  #    get "#{charity.filename.gsub("_", "")}", to: redirect("/charities/#{charity.id}")
  #  end
  #  
  #  get "greenpledge", to: redirect("/charities/#{Charity.find_by(name: "The Green Pledge").id}")
  #  get "habitat", to: redirect("/charities/#{Charity.find_by(name: "Habitat for Humanity Australia").id}")
  #  get "ms", to: redirect("/charities/#{Charity.find_by(name: "MS Australia").id}")
  #  get "onemillionwomen", to: redirect("/charities/#{Charity.find_by(name: "1 Million Women").id}")
  #  get "1millionwomen", to: redirect("/charities/#{Charity.find_by(name: "1 Million Women").id}")
  
  get "ethicalpower", to: redirect("/switches/ethical_power")
  get "ethical-power", to: redirect("/switches/ethical_power")
  
  get "ethicalsuper", to: redirect("/switches/ethical_super")
  get "ethical-super", to: redirect("/switches/ethical_super")
  
  get "ethicalhomeloans", to: redirect("/switches/ethical_homeloans")
  get "ethical-homeloans", to: redirect("/switches/ethical_homeloans")
end

app/views/admin/admin.html.erb
<% if current_user && current_user.admin %>
  <div class="row text-page-header mb40 text-s">
    <div class="col-sm-8 col-sm-offset-2">
      <%= link_to "Dashboard", admin_path %>
    </div>
    
    <div class="clb"></div>
  </div>
  
  <div class="admin row mb40 tac">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="col-sm-6 p10">
        <%= link_to admin_switchers_path do %>
          <div class="admin-button">
            Switchers
          </div>
        <% end %>
      </div>

      <div class="col-sm-6 p10">
        <%= link_to admin_messages_path do %>
          <div class="admin-button">
            Messages
          </div>
        <% end %>
      </div>

      <div class="col-sm-6 p10">
        <%= link_to admin_subscribers_path do %>
          <div class="admin-button">
            Subscribers
          </div>
        <% end %>
      </div>

      <div class="col-sm-6 p10">
        <%= link_to admin_faqs_path do %>
          <div class="admin-button">
            FAQs
          </div>
        <% end %>
      </div>
      
      <div class="clb"></div>
    </div>
    
    <div class="clb"></div>
  </div>
<% else %>
  <div class="tac">You are not authorized to view this page</div>
<% end %>

app/views/admin/faqs.html.erb
<% if current_user && current_user.admin %>  
  <div class="row text-page-header mb40 text-s">
    <div class="col-sm-8 col-sm-offset-2">
      <%= link_to "Dashboard", admin_path %> > FAQs
    </div>
    
    <div class="clb"></div>
  </div>
  
  <div class="faqs admin col-sm-8 col-sm-offset-2">
    <h2 class="mb20">FAQs <%= link_to "Add New", admin_new_faq_path, class: "btn btn-primary flr" %></h2>

    <% @faqs.each do |faq| %>
      <%= render "faqs/faq_admin", faq: faq %>
    <% end %>
  </div>
<% else %>
  <div class="tac">You are not authorized to view this page</div>
<% end %>

app/views/admin/messages.html.erb
<% if current_user && current_user.admin %>
  <div class="row text-page-header mb40 text-s">
    <div class="col-sm-8 col-sm-offset-2">
      <%= link_to "Dashboard", admin_path %> > Messages
    </div>
    
    <div class="clb"></div>
  </div>
  
  <div class="messages col-sm-10 col-sm-offset-1">
    <h2 class="mb20">Messages</h2>

    <div class="row">
      <%= render @messages %>
    </div>
  </div>
<% else %>
  <div class="tac">You are not authorized to view this page</div>
<% end %>

app/views/admin/new_faq.html.erb
<% if current_user && current_user.admin %>
  <div class="row text-page-header mb40 text-s">
    <div class="col-sm-8 col-sm-offset-2">
      <%= link_to "Dashboard", admin_path %> > <%= link_to "FAQs", admin_faqs_path %> > New FAQ
    </div>
    
    <div class="clb"></div>
  </div>
  
  <div class="col-sm-8 col-sm-offset-2 mb40">
    <%= render 'faqs/form' %>
  </div>
<% else %>
  <div class="tac">You are not authorized to view this page</div>
<% end %>

app/views/admin/subscribers.html.erb
<% if current_user && current_user.admin %>
  <div class="row text-page-header mb40 text-s">
    <div class="col-sm-8 col-sm-offset-2">
      <%= link_to "Dashboard", admin_path %> > Subscribers
    </div>
    
    <div class="clb"></div>
  </div>
  
  <div class="subscribers admin col-sm-10 col-sm-offset-1">
    <h2 class="mb20">Subscribers</h2>

    <table class="w100p">
      <thead>
        <tr class="tal">
          <th class="col-sm-6">Email</th>
          <th class="col-sm-6">Postcode</th>
        </tr>
      </thead>

      <tbody>
        <%= render @subscribers %>
      </tbody>
    </table>
  </div>  
<% else %>
  <div class="tac">You are not authorized to view this page</div>
<% end %>

app/views/admin/switchers.html.erb
<% if current_user && current_user.admin %>
  <div class="row text-page-header mb40 text-s">
    <div class="col-sm-8 col-sm-offset-2">
      <%= link_to "Dashboard", admin_path %> > Switchers
    </div>
    
    <div class="clb"></div>
  </div>
  
  <div class="switches admin col-sm-10 col-sm-offset-1 mb40">
    <h2 class="mb20">Switchers</h2>

    <table class="w100p text-s">
      <thead>
        <tr class="tal">
          <th class="col-sm-2">Name</th>
          <th class="col-sm-2">Email</th>
          <th class="col-sm-2">Postcode/Phone</th>
          <th class="col-sm-2">Charity Choice</th>
          <th class="col-sm-2">Partner Choice</th>
          <th class="col-sm-2">Status</th>
        </tr>
      </thead>

      <tbody>
        <%= render @switches %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="tac">You are not authorized to view this page</div>
<% end %>