config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'statics#home'
  
  get '/terms_and_conditions', to: 'statics#terms_and_conditions'
  get '/privacy_policy', to: 'statics#privacy_policy'
  get '/criteria_table_info', to: 'statics#criteria_table_info'
  get '/admin', to: 'admin#admin'
  get '/admin/messages', to: 'admin#messages'
  get '/admin/switchers', to: 'admin#switchers'
  get '/admin/subscribers', to: 'admin#subscribers'
  get '/admin/faqs', to: 'admin#faqs'
  get '/admin/new_faq', to: 'admin#new_faq'
  get '/placeholder', to: 'statics#placeholder'
  post '/home_switch', to: 'statics#home_switch'
  post '/change_state', to: 'power_providers#change_state'
  
  resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :faq_tags, only: [:create, :destroy]
  resources :messages, only: [:new, :create]
  resources :partners, only: [:new, :show]
  resources :charities, only: [:show]
  resources :power_providers, only: [:index]
  resources :subscribers, only: [:create]
  
  resources :switches, only: [:new, :create, :update] do
    get 'ethical_power', on: :collection
    get 'ethical_super', on: :collection
    get 'ethical_homeloans', on: :collection
    get 'homeloans_sent', on: :collection
  end
  
  # Legacy routes
  
  #  Charity.all.each do |charity|
  #    get "#{charity.filename.gsub("_", "")}", to: redirect("/charities/#{charity.id}")
  #  end
  #  
  #  get "greenpledge", to: redirect("/charities/#{Charity.find_by(name: "The Green Pledge").id}")
  #  get "habitat", to: redirect("/charities/#{Charity.find_by(name: "Habitat for Humanity Australia").id}")
  #  get "ms", to: redirect("/charities/#{Charity.find_by(name: "MS Australia").id}")
  #  get "onemillionwomen", to: redirect("/charities/#{Charity.find_by(name: "1 Million Women").id}")
  #  get "1millionwomen", to: redirect("/charities/#{Charity.find_by(name: "1 Million Women").id}")
  
  get "ethicalpower", to: redirect("/switches/ethical_power")
  get "ethical-power", to: redirect("/switches/ethical_power")
  
  get "ethicalsuper", to: redirect("/switches/ethical_super")
  get "ethical-super", to: redirect("/switches/ethical_super")
  
  get "ethicalhomeloans", to: redirect("/switches/ethical_homeloans")
  get "ethical-homeloans", to: redirect("/switches/ethical_homeloans")
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  skip_before_filter :redirect_to_placeholder, only: [:placeholder]

  def home
    @charities = Charity.currently_live.order("created_at DESC")
    @switch = Switch.new
    @states = State.all
    
    assign_partner_variables
  end
  
  def terms_and_conditions
    
  end
  
  def privacy_policy
    
  end
  
  def home_switch
    case params[:switch_type]
    when "power"
      redirect_to ethical_power_switches_path(state_id: params[:state_id])
    when "super"
      redirect_to ethical_super_switches_path(state_id: params[:state_id])
    when "homeloan"
      redirect_to ethical_homeloans_switches_path(state_id: params[:state_id])
    end
  end
  
  def placeholder
  end
end

app/views/statics/_banner_home.html.erb
<section class="banner banner-tall row flex-center" style="background-image:url(<%= image_url "banner_home.jpg" %>)">
  <div class="faded-white col-sm-6 col-sm-offset-3 tac p30">
    <h1>Switch to the companies that deserve your money</h1>
    
    <div class="row">
      <%= form_tag(home_switch_path, method: :post) do %>
        <div class="col-sm-6 col-sm-offset-3">
          <%= select_tag :state_id, options_from_collection_for_select(State.all, "id", "short_name"), prompt: "Select State...", class: "form-control di mb0" %>
          
          <div id="state_error" class="error-text mt20" style="display:none"></div>
        </div>
        
        <%= hidden_field_tag :switch_type %>

        <div class="clb"></div>

        <p>Choose a switch type to get started:</p>

        <div class="col-xs-4 p10">
          <div class="btn-switch-icon" data-switch-type="power">
            <%= image_tag "icon_power.png" %>
            <p class="text-m">Power Provider</p>
          </div>
        </div>

        <div class="col-xs-4 p10">
          <div class="btn-switch-icon" data-switch-type="super">
            <%= image_tag "icon_super.png" %>
            <p class="text-m">Super Fund</p>
          </div>
        </div>

        <div class="col-xs-4 p10">
          <div class="btn-switch-icon" data-switch-type="homeloan">
            <%= image_tag "icon_homeloans.png" %>
            <p class="text-m">Home Loan</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/statics/_criteria.html.erb
<section id="switches" class="row pb50 pt50 por">
  <h2 class="mb20 tac">What Makes an Ethical Company?</h2>

  <div class="col-sm-8 col-sm-offset-2 mb20 tac">
    We believe that the money you spend every day can have a <strong>positive effect</strong> and that you have the right to know that your money <strong>isn't doing any harm</strong>. We find the companies that tick these boxes whilst still being affordable with a great customer experience. Individually, here are just some of the factors we consider:
  </div>

  <%= render 'statics/popups' %>
  
  <div class="tac pl20 pr20">
    <div class="col-sm-4 p10">
      <div class="brdr-grey bxsh pl15 pr15 pt20 pb15 white-bg">
        <h3 class="mb20">Power providers</h3>

        <div class="col-sm-4 col-sm-offset-4">
          <%= image_tag "icon_power.png", class: "w100p w50p-sm" %>
        </div>

        <div class="clb mb20"></div>

        <div class="text-s">
          <div class="col-xs-4">
            <%= image_tag "reasons_renewable.png", class: "w80p" %>
            <p>Renewable Energy</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_leaf.png", class: "w80p" %>
            <p>Carbon Emissions</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_csg.png", class: "w80p" %>
            <p>No CSG investment</p>
          </div>
          
          <div class="clb"></div>

          <div class="col-xs-4">
            <%= image_tag "reasons_ombudsman.png", class: "w80p" %>
            <p>Ombudsman complaints</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_smiley.png", class: "w80p" %>
            <p>Customer experience</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_contract.png", class: "w80p" %>
            <p>Favourable contracts</p>
          </div>
        </div>

        <div class="clb mb20"></div>

        <p class="mb10">
          <%= link_to "Choose a Provider", "#switches", class: "btn btn-primary btn-padded popup_reveal", id: "switch_power_button" %>
        </p>

        <p class="text-s">
          <%= link_to "Or find out more", ethical_power_switches_path %>
        </p>

        <div class="clb"></div>
      </div>
    </div>

    <div class="col-sm-4 p10">
      <div class="brdr-grey bxsh pl15 pr15 pt20 pb15 white-bg">
        <h3 class="mb20">Super Funds</h3>

        <div class="col-sm-4 col-sm-offset-4">
          <%= image_tag "icon_super.png", class: "w100p w50p-sm" %>
        </div>

        <div class="clb mb20"></div>

        <div class="text-s">
          <div class="col-xs-4">
            <%= image_tag "reasons_renewable_energy_green.png", class: "w80p" %>
            <p>Renewable Energy</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_education_green.png", class: "w80p" %>
            <p>Education</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_healthcare_green.png", class: "w80p" %>
            <p>Healthcare</p>
          </div>
          
          <div class="clb"></div>

          <div class="col-xs-4">
            <%= image_tag "reasons_fossil_fuels_red.png", class: "w80p" %>
            <p>Fossil fuel divestment</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_weapons_red.png", class: "w80p" %>
            <p>Weapons</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_tobacco_red.png", class: "w80p" %>
            <p>Tobacco</p>
          </div>
        </div>

        <div class="clb mb20"></div>

        <p class="mb10">
          <%= link_to "Choose a Provider", "#switches", class: "btn btn-primary btn-padded popup_reveal", id: "switch_super_button" %>
        </p>

        <p class="text-s">
          <%= link_to "Or find out more", ethical_super_switches_path %>
        </p>

        <div class="clb"></div>
      </div>
    </div>

    <div class="col-sm-4 p10">
      <div class="brdr-grey bxsh pl15 pr15 pt20 pb15 white-bg">
        <h3 class="mb20">Home loans <sup>new!</sup></h3>

        <div class="col-sm-4 col-sm-offset-4">
          <%= image_tag "icon_homeloans.png", class: "w100p w50p-sm" %>
        </div>

        <div class="clb mb20"></div>

        <div class="text-s">
          <div class="col-xs-4">
            <%= image_tag "reasons_renewable_energy_green.png", class: "w80p" %>
            <p>Renewable Energy</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_medical_science_green.png", class: "w80p" %>
            <p>Medical science</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_responsible_banking_green.png", class: "w80p" %>
            <p>Responsible banking</p>
          </div>
          
          <div class="clb"></div>

          <div class="col-xs-4">
            <%= image_tag "reasons_logging_red.png", class: "w80p" %>
            <p>Logging</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_exploitation_red.png", class: "w80p" %>
            <p>Human rights abuses</p>
          </div>

          <div class="col-xs-4">
            <%= image_tag "reasons_gambling_red.png", class: "w80p" %>
            <p>Gambling</p>
          </div>
        </div>

        <div class="clb mb20"></div>

        <p class="mb10">
          <%= link_to "Register Interest", "#switches", class: "btn btn-primary btn-padded popup_reveal", id: "switch_homeloans_button" %>
        </p>

        <p class="text-s">
          <%= link_to "Or find out more", ethical_homeloans_switches_path %>
        </p>

        <div class="clb"></div>
      </div>
    </div>

    <div class="clb"></div>
  </div>
</section>

app/views/statics/_how_ethical_is_your_power_provider.html.erb
<div class="highlight-bg row white-text pt20 pb20 tac mb40">
  <div class="lh50 col-sm-8 col-sm-offset-2">
    <div class="col-sm-6 tar tac-sm">
      <h3 class="fwn">How ethical is your power company?</h3>
    </div>

    <%= form_tag(power_providers_path, method: :get) do %>
      <div class="col-sm-3">
        <%= select_tag :state_id, options_from_collection_for_select(@states, "id", "short_name"), prompt: "Select State...", class: "form-control di" %>
      </div>
      
      <div class="col-sm-3 tal tac-sm">
        <%= submit_tag "Find Out Now", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  
  <div class="clb"></div>
</div>

app/views/statics/_our_story.html.erb
<section class="our-story row">
  <div class="faded-blue pt40 pb40 tac mb30">
    <h2>Our Story</h2>
  </div>

  <div class="col-sm-4 col-sm-offset-2 faded-blue pt10 pb10 pl20 pr20">
    <p>
      Ethical Switch began because we noticed something. No matter how hard we try, the task of consuming ethically is difficult and time-consuming.  Our purpose is to help busy people discover companies that align better with their personal values.
    </p>

    <p>
      Through our research, we empower consumers with the information needed to make their ethical choices.  We then provide a simple, online and fast switch.
    </p>

    <p>
      Our focus is with core household spending –electricity, superannuation and soon to be released, banking!  Choosing more ethical providers can vastly reduce personal carbon footprints and helps reward companies that are doing better business.
    </p>

    <p>
      Unlike other comparison websites, we only offer switches to companies that rate more highly across a range of ethical considerations.  We also made sure that a vast portion of our profits go to our charity partners - every time somebody makes a switch, we donate.
    </p>

    <p>
      Based in Melbourne, we were incubated by a group of passionate volunteers in 2014.  The heart of our business is to empower our awesome not-for-profit partners and that's why we donate over 90% of our profits!
    </p>
  </div>
		
  <div class="col-sm-4 col-sm-offset-1 faded-blue pt10 pb10 pl20 pr20">
    <h3 class="mt10">Our team:</h3>

    <p>
      Sam – passionate about “business for purpose”, holds an MBA from Melbourne Business School and has worked in the comercial and not-for-profit sectors.
    </p>

    <p>
      Tam – worked for 14 years in the energy markets with a passion for renewable energy.  Has founded multiple social enterprises in Australia and Africa.
    </p>

    <p>
      Dan – aims to make the world a better place through technology, has worked with multiple not-for-profits to give their dreams a digital voice.
    </p>

    <p>
      We hope you enjoy our service and that after you've made your first switch you'll agree that switching never felt better.
    </p>
  </div>
  
  <div class="clb"></div>
</section>

app/views/statics/_popups.html.erb
<div id="switch_power" class="popup" style="display:none;">
  <div class="close"></div>

  <header class="tac">
    <h2 class="tac-sm">Switch your power provider</h2>
  
    <p class="col-sm-8 col-sm-offset-2">We have done our research and found the greenest, fairest, most ethical power providers in Australia. To view our full criteria and compare the ethics of all power providers, check out our <%= link_to "power criteria table", power_providers_path, class: "link" %>.</p>
  </header>

  <%= render 'statics/switch_options_power' %>
</div>
 
<div id="switch_super" class="popup" style="display:none;">
  <div class="close"></div>

  <header class="tac">
    <h2 class="tac-sm">Switch your super provider</h2>
  
    <p class="col-sm-8 col-sm-offset-2">We have done our research and partnered up with three super funds who are committed to investing only in companies that are having a positive impact on the world.</p>
  </header>

  <%= render 'statics/switch_options_super' %>
</div>
 
<div id="switch_homeloans" class="popup" style="display:none;">
  <div class="close"></div>

  <header class="tac">
    <h2 class="tac-sm">Switch your homeloan</h2>
  
    <p class="col-sm-8 col-sm-offset-2">For most people a home loan is the largest investment they will ever make. Making sure that the money is used by banks who make positive investments is one of the most impactful things that we can do to help create a positive, sustainable society.</p>
  
    <div class="clb"></div>

    <p class="col-sm-8 col-sm-offset-2">Simply fill out the form below and a member of the Ethical Homeloans team will get in touch to discuss the switching process</p>
  </header>

  <div class="col-sm-8 col-sm-offset-2">
    <%= render 'switches/form', partner: @ethical_homeloans, switch: @switch %>
  </div>
</div>

app/views/statics/_sign_up_bar.html.erb
<div class="highlight-bg row white-text pt20 pb20 tac mb40">
  <div id="signup_content">
    <h3 class="fwn mb20">Sign Up Now for Updates on New Ethical Products and Services!</h3>

    <%= form_for(Subscriber.new, remote: true) do |f| %>
      <%= f.email_field :email, placeholder: "Email", class: "form-control di wi" %>
      <%= f.text_field :postcode, placeholder: "Postcode", class: "form-control di wi" %>
      <%= f.submit "Submit", class: "btn btn-primary form-control di wi vab mb10", id: "signup_submit" %>
    <% end %>
    
    <div id="subscriber_error" class="text-s" style="display:none"></div>
  </div>
</div>

app/views/statics/_switch_options.html.erb
<section id="switches" class="row tac mb40 por">
  <%= render 'statics/popups' %>
  
  <div id="popup_anchor" class="<%= no_super ? "col-sm-6" : "col-sm-4" %> p10">
    <div class="grey-padded">
      <h3>Switch your power provider</h3>
      
      <p class="col-sm-10 col-sm-offset-1 mb20">Choose a power provider that cares about both you and the environment.</p>
    
      <div class="col-sm-4 col-sm-offset-4 mb20">
        <%= image_tag "icon_power.png", class: "w100p w40p-sm" %>
      </div>
      
      <div class="clb"></div>
      
      <p class="mb10">
        <%= link_to "Choose a Provider", "#popup_anchor", class: "btn btn-primary btn-padded popup_reveal", id: "switch_power_button" %>
      </p>
      
      <p class="text-s">
        <%= link_to "Or find out more", ethical_power_switches_path %>
      </p>
      
      <div class="clb"></div>
    </div>
  </div>
  
  <% unless no_super %>
    <div class="col-sm-4 p10">
      <div class="grey-padded">
        <h3>Switch your super fund</h3>

        <p class="col-sm-10 col-sm-offset-1 mb20">Make sure your super funds only positive investments and companies.</p>

        <div class="col-sm-4 col-sm-offset-4 mb20">
          <%= image_tag "icon_super.png", class: "w100p w40p-sm" %>
        </div>

        <div class="clb"></div>

        <p class="mb10">
          <%= link_to "Choose a Provider", "#popup_anchor", class: "btn btn-primary btn-padded popup_reveal", id: "switch_super_button" %>
        </p>

        <p class="text-s">
          <%= link_to "Or find out more", ethical_super_switches_path %>
        </p>

        <div class="clb"></div>
      </div>
    </div>
  <% end %>
  
  <div class="<%= no_super ? "col-sm-6" : "col-sm-4" %> p10">
    <div class="grey-padded">
      <h3>Switch your homeloan</h3>
      
      <p class="col-sm-10 col-sm-offset-1 mb20">Make sure your biggest investment is having a positive effect on the world.</p>
    
      <div class="col-sm-4 col-sm-offset-4 mb20">
        <%= image_tag "icon_homeloans.png", class: "w100p w40p-sm" %>
      </div>
      
      <div class="clb"></div>
      
      <p class="mb10">
        <%= link_to "Choose a Provider", "#popup_anchor", class: "btn btn-primary btn-padded popup_reveal", id: "switch_homeloans_button" %>
      </p>
      
      <p class="text-s">
        <%= link_to "Or find out more", ethical_homeloans_switches_path %>
      </p>
      
      <div class="clb"></div>
    </div>
  </div>
  
  <div class="clb"></div>
</section>

app/views/statics/_switch_options_power.html.erb
<div class="df w100p switch_options tac db-sm">
  <div class="flex p10">
    <div class="grey-padded h100p df fdc">
      <div class="tac">
        <%= image_tag "partner_powershop_full_transparent.png" %>
      </div>

      <p class="text-s">Available in <b>VIC, NSW &amp; SE-QLD</b></p>

      <ul class="provider-checklist">
        <li>
          100% renewable energy
        </li>

        <li>
          Zero carbon emissions
        </li>

        <li>
          No lock-in contracts
        </li>

        <li>
          Will pay exit fee from your current contract
          <%= image_tag "help.png", rel: "tooltip", title: 'Up to $75, which covers almost every possible contract <br> <span class="tooltip-tap">Tap to close</span>' %>
        </li>

        <li>
          Ranked <b>Australia's greenest provider</b> by Greenpeace two years running
        </li>
      </ul>

      <div>
        <% if @state && (@state.short_name == "VIC" || @state.short_name == "NSW" || @state.short_name == "QLD") %>
          <p class="text-success">Available in <%= @state.name %>!</p>
        <% end %>
        
        <p class="mt0"><%= link_to "Choose Powershop", new_switch_path(partner_id: @powershop.id, charity_id: (@charity && @charity.name != "Healthy Futures") ? @charity.id : nil), class: "btn btn-primary btn-padded" %></p>
        <p><%= link_to "Or find out more about Powershop", partner_path(@powershop), class: "text-s" %></p>
      </div>
    </div>
  </div>

  <div class="flex p10">
    <div class="grey-padded h100p df fdc">
      <div class="tac">
        <%= image_tag "partner_energy_locals_full.png" %>
      </div>

      <p class="text-s">Available in <b>NSW &amp; QLD</b></p>

      <ul class="provider-checklist">
        <li>
          Promise to never raise prices for profit reasons
        </li>

        <li>
          Donate over half their profits to charity
        </li>

        <li>
          No lock-in contracts
        </li>

        <li>
          Fixed prices until July 2018
        </li>

        <li class="no-tick text-s">
          Note: If you're wondering why we don't mention renewables it's because Energy Locals do not own generators!
        </li>
      </ul>

      <div>
        <% if @state && (@state.short_name == "NSW" || @state.short_name == "QLD") %>
          <p class="text-success">Available in <%= @state.name %>!</p>
        <% end %>
        
        <p><%= link_to "Choose Energy Locals", new_switch_path(partner_id: @energy_locals.id, charity_id: @charity ? @charity.id : nil), class: "btn btn-primary btn-padded" %></p>

        <p><%= link_to "Or find out more about Energy Locals", partner_path(@energy_locals), class: "text-s" %></p>
      </div>
    </div>
  </div>

  <div class="flex p10">
    <div class="grey-padded h100p df fdc">
      <div class="tac">
        <%= image_tag "partner_diamond_energy_full.png" %>
      </div>

      <p class="text-s">Available in <b>VIC, NSW, SA &amp; QLD</b></p>

      <ul class="provider-checklist">
        <li>
          Solar specialists
        </li>

        <li>
          100% renewable energy
        </li>

        <li>
          Zero carbon emissions
        </li>

        <li>
          5 star Greenpeace electricity supplier, highly rated since 2009
        </li>
      </ul>

      <div>
        <% if @state && (@state.short_name == "VIC" || @state.short_name == "NSW" || @state.short_name == "QLD" || @state.short_name == "SA") %>
          <p class="text-success">Available in <%= @state.name %>!</p>
        <% end %>
        
        <p><%= link_to "Choose Diamond Energy", new_switch_path(partner_id: @diamond_energy.id, charity_id: @charity ? @charity.id : nil), class: "btn btn-primary btn-padded" %></p>

        <p><%= link_to "Or find out more about Diamond Energy", partner_path(@diamond_energy), class: "text-s" %></p>
      </div>
    </div>
  </div>
</div>

app/views/statics/_switch_options_super.html.erb
<div class="df w100p switch_options tac db-sm">
<!--
  <div class="flex p10">
    <div class="grey-padded h100p df fdc">
      <div class="tac">
        <%#= image_tag "partner_australian_ethical_full.png" %>
      </div>

      <ul class="provider-checklist">
        <li>
          Positive, competitive investments
        </li>

        <li>
          Avoid companies involved in anything harmful
        </li>

        <li>
          Invest in positive industries such as clean energy and education
        </li>

        <li>
          Fastest Growing Super Fund in Australia
        </li>
      </ul>

      <p><%#= link_to "Choose Australian Ethical", new_switch_path(partner_id: @australian_ethical.id, charity_id: @charity ? @charity.id : nil), class: "btn btn-primary btn-padded" %></p>

      <p><%#= link_to "Or find out more about Australian Ethical", partner_path(@australian_ethical), class: "text-s" %></p>
    </div>
  </div>
-->

  <div class="flex p10">
    <div class="grey-padded h100p df fdc">
      <div class="tac">
        <%= image_tag "partner_good_super_full.png" %>
      </div>

      <ul class="provider-checklist">
        <li>
          Positive investments such as sustainable products, clean energy and healthcare
        </li>

        <li>
          Avoid damaging and unethical investments
        </li>

        <li>
          Quick and simple online switch
        </li>
      </ul>

      <p><%= link_to "Choose Good Super", new_switch_path(partner_id: @good_super.id, charity_id: @charity ? @charity.id : nil), class: "btn btn-primary btn-padded" %></p>

      <p><%= link_to "Or find out more about Good Super", partner_path(@good_super), class: "text-s" %></p>
    </div>
  </div>

  <div class="flex p10">
    <div class="grey-padded h100p df fdc">
      <div class="tac">
        <%= image_tag "partner_future_super_full.png" %>
      </div>

      <ul class="provider-checklist">
        <li>
          Australia's ONLY super fund with no investment in fossil fuels
        </li>

        <li>
          Switch online now in under 3 minutes
        </li>

        <li>
          First carbon neutral certified super fund in the world
        </li>

        <li>
          Support only approved, ethical investments
        </li>
      </ul>

      <p><%= link_to "Choose Future Super", new_switch_path(partner_id: @future_super.id, charity_id: @charity ? @charity.id : nil), class: "btn btn-primary btn-padded" %></p>

      <p><%= link_to "Or find out more about Future Super", partner_path(@future_super), class: "text-s" %></p>
    </div>
  </div>
</div>

app/views/statics/_three_steps.html.erb
<section class="row teal-pattern-bg pt40 pb40">
  <h2 class="text-l tac mb20">Switch in 5 minutes and 3 simple steps:</h2>
  
  <div class="pl10-sm pr10-sm">
    <div class="col-sm-4 col-sm-offset-4 white-bg brdr-grey">
      <ul class="listdc">
        <li>Choose your new ethical provider</li>
        <li>Fill your name and email details</li>
        <li>Finish on your new providers website</li>
        <% if controller_name == "charities" %>
          <li class="text-success mt10">We make a donation to <%= @charity.name %>!</li>
        <% end %>
      </ul>
    </div>
  </div>
  
  <div class="clb"></div>
</section>

app/views/statics/home.html.erb
<%= render 'banner_home' %>
<%= render 'three_steps' %>
<%= render 'criteria' %>
<%= render 'sign_up_bar' %>
<%= render 'charity_partners' %>
<%= render 'how_ethical_is_your_power_provider' %>
<%= render 'testimonials' %>
<%= render 'our_story' %>

app/views/statics/placeholder.html.erb
<div class="placeholder row">
  <h1>Ethical Switch is no longer active</h1>
  
  <p>Thanks so much to everyone who supported us! It's been a pleasure helping you switch to greener, cleaner, and more ethical suppliers.</p>
  
  <p>All the best,</p>
  
  <p>The Ethical Switch team</p>
</div>

app/views/statics/terms_and_conditions.html.erb
<div class="text-page">
  <header class="row flex-center">
    <h1 class="tac">Terms &amp; Conditions</h1>
  </header>

  <main class="col-sm-8 col-sm-offset-2">
    <p>
      Each time you access the Ethical Switch web site you confirm you have read and agree to these terms and conditions (Terms and Conditions of Use). 
      Ethical Switch may from time to time change these Terms and Conditions of Use.
    </p>

    <h3>Use of Your Information</h3>

    <p>
      You acknowledge and agree that Ethical Switch may use your personal information in accordance with the Ethical Switch Privacy Policy which can be found 
      <%= link_to "on our website", privacy_policy_path, class: "link" %>.
    </p>

    <h3>Providers</h3>

    <p>
      Ethical Switch decides on the providers of the goods or services for each of our campaigns through research of the company and their goods and services to
      ensure they are aligned with the Ethical Switch values and are providing socially aware and sustainable products. Ethical Switch takes appropriate measures 
      to ensure that our providers follow our principles of being sustainable, but Ethical Switch carries no liability if the provider does or offers something 
      that is not in line with our guidelines for products that are socially aware and environmentally sustainable.
    </p>

    <p>
      Customers are not obligated to act on any advice given by Ethical Switch, the final decision to change products or suppliers remains entirely up to the customer.
    </p>

    <h3>Limitation of Liability</h3>

    <ul>

      <li>
        Ethical Switch has taken all reasonable steps to ensure the accuracy of the information on this website;
      </li>

      <li>
        Some of the information available on our website may be provided by external sources and hence there may be some inaccuracies in the website over which we 
        have no control;
      </li>

      <li>Ethical Switch does not warrant or guarantee the:</li>

        <ul>

          <li>
            timeliness, accuracy or completeness of the website information;
          </li>

          <li>
            the quality of the results obtained from the use of the website.
          </li>

        </ul>

      <li>
        Ethical Switch carries no liability of the website recommendations offered to consumers from our providers. If you are unsure of the deal being offered 
        through the website by the third party provider, you should ask either Ethical Switch or the third party provider for more information to ensure you 
        understand the full terms and conditions of the deal being offered.
      </li>

      <li>
        Ethical Switch will pass on your personal information to our providers if you agree to go ahead with the deal. However, Ethical Switch holds no 
        responsibility for the amount of time the provider takes to deliver the particular good or service that you have signed up for. This should be 
        discussed with the provider.
      </li>

    </ul>

    <h3>Commissions</h3>

    <p>
      Ethical Switch receives commissions from our third party providers of goods or services which is negotiated as part of the deal that we have offered 
      customers. As Ethical Switch is a social enterprise, a significant portion of our commissions will be gifted to the charities in accordance with our 
      customers' choice which they choose as one of the steps on the website.
    </p>

    <p>
      Customers are not required to pay Ethical Switch for our service.
    </p>

    <h3>Ammendments</h3>

    <p>
      Ethical Switch may at any time and at Ethical Switch's absolute discretion vary these Conditions of Use.
    </p>
  </main>
</div>