config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'statics#home'
  
  get '/terms_and_conditions', to: 'statics#terms_and_conditions'
  get '/privacy_policy', to: 'statics#privacy_policy'
  get '/criteria_table_info', to: 'statics#criteria_table_info'
  get '/admin', to: 'admin#admin'
  get '/admin/messages', to: 'admin#messages'
  get '/admin/switchers', to: 'admin#switchers'
  get '/admin/subscribers', to: 'admin#subscribers'
  get '/admin/faqs', to: 'admin#faqs'
  get '/admin/new_faq', to: 'admin#new_faq'
  get '/placeholder', to: 'statics#placeholder'
  post '/home_switch', to: 'statics#home_switch'
  post '/change_state', to: 'power_providers#change_state'
  
  resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :faq_tags, only: [:create, :destroy]
  resources :messages, only: [:new, :create]
  resources :partners, only: [:new, :show]
  resources :charities, only: [:show]
  resources :power_providers, only: [:index]
  resources :subscribers, only: [:create]
  
  resources :switches, only: [:new, :create, :update] do
    get 'ethical_power', on: :collection
    get 'ethical_super', on: :collection
    get 'ethical_homeloans', on: :collection
    get 'homeloans_sent', on: :collection
  end
  
  # Legacy routes
  
  #  Charity.all.each do |charity|
  #    get "#{charity.filename.gsub("_", "")}", to: redirect("/charities/#{charity.id}")
  #  end
  #  
  #  get "greenpledge", to: redirect("/charities/#{Charity.find_by(name: "The Green Pledge").id}")
  #  get "habitat", to: redirect("/charities/#{Charity.find_by(name: "Habitat for Humanity Australia").id}")
  #  get "ms", to: redirect("/charities/#{Charity.find_by(name: "MS Australia").id}")
  #  get "onemillionwomen", to: redirect("/charities/#{Charity.find_by(name: "1 Million Women").id}")
  #  get "1millionwomen", to: redirect("/charities/#{Charity.find_by(name: "1 Million Women").id}")
  
  get "ethicalpower", to: redirect("/switches/ethical_power")
  get "ethical-power", to: redirect("/switches/ethical_power")
  
  get "ethicalsuper", to: redirect("/switches/ethical_super")
  get "ethical-super", to: redirect("/switches/ethical_super")
  
  get "ethicalhomeloans", to: redirect("/switches/ethical_homeloans")
  get "ethical-homeloans", to: redirect("/switches/ethical_homeloans")
end

app/models/power_provider.rb
class PowerProvider < ApplicationRecord
  has_many :power_provider_states
  has_many :states, through: :power_provider_states
  has_many :termination_fees
  
  def filename
    self.name.downcase.gsub(" ", "_")
  end
  
  def partner?
    self.filename == "powershop" || self.filename == "diamond_energy" || self.filename == "energy_locals"
  end
  
  def dirty_three?
    self.filename == "origin_energy" || self.filename == "agl_energy" || self.filename == "energy_australia"
  end
  
  def prechecked?(state)
    self.partner? || self.dirty_three? || (self.filename == "aurora_energy" && (state && state.short_name == "TAS"))
  end
  
  def extra_details(provider_name)
    case provider_name
    when "powershop"
      "<ul class='lisn'><li><strong>Switch through Ethical Switch and we will make a donation to charity!</strong></li><li>Commonly have the lowest prices in VIC! #{ActionController::Base.helpers.image_tag("help.png", rel: "tooltip", title: "The Essential Services commission stated in a Dec '14 report 'taking into account all available discounts, the lowest overall prices were most commonly available from Powershop' <br /> <span class='tooltip-tap'>Tap to close</span>")}</li><li>If you\'re stuck in a contract, Powershop will pay your exit fees! #{ActionController::Base.helpers.image_tag("help.png", rel: "tooltip", title: "Up tp $75, which covers almost every residential contract <br /> <span class=&quot;tooltip-tap&quot;>Tap to close</span>")}</li><li>Awesome phone app to track usage/pay bills</li></ul>".html_safe
    when "energy_locals"
      '<ul class="lisn"><li><strong>Switch through Ethical Switch and we will make a donation to charity!</strong></li><li>Fixed prices until July 2018</li><li>A company promise to never raise prices for profit reasons!</li><li>Donate over half their profits to charity.</li><li>No lock in contracts</li></ul>'.html_safe
    when "diamond_energy"
      '<ul class="lisn"><li><strong>Switch through Ethical Switch and we will make a donation to charity!</strong></li><li>Excellent offers, feed in rates and service for solar customers</li><li>Great customer service</li></ul>'.html_safe
    else
      nil
    end
  end
end

app/controllers/power_providers_controller.rb
class PowerProvidersController < ApplicationController
  def index
    set_power_criteria(params[:state_id] || nil)
  end
  
  def change_state
    set_power_criteria(params[:state_id] || nil)
    
    respond_to do |format|
      format.js
    end
  end
end

app/views/power_providers/_criteria_table.html.erb
<div id="power_criteria_container">
  <% unless action_name == "ethical_power" %>
    <div class="highlight-bg row pt20 pb20 tac text-white">
      <h3>Showing Results for <%= @state ? @state.short_name : "Australia" %>:</h3>
    </div>
  <% end %>
  
  <div class="row grey-bg pt5 pb5">
    <%= form_tag(change_state_path, remote: true) do %>
      <div class="tac" style="line-height:40px;">
        
        <%= @state ? "Change state:" : "Filter by state:" %>
      
        <%= select_tag :state_id, options_from_collection_for_select(State.all, "id", "short_name", selected: @state ? @state.id : nil), prompt: "Select State...", class: "form-control di w200 mb0" %>
      </div>
    <% end %>
    
    <div class="clb"></div>
  </div>

  <div class="criteria_table">
    <div class="tablet-desktop">
      <form id="toggler">
        <div class="cta">
          Compare your providers:
        </div>

        <% @power_providers.each do |power_provider| %>
          <div class="checkboxItem">
            <input type="checkbox" id="<%= power_provider.filename %>" name="<%= power_provider.filename %>" value="<%= power_provider.name %>" class="di" <%= "disabled" if power_provider.partner? %> <%= "checked" if power_provider.prechecked?(@state) %>>
            <label for="<%= power_provider.filename %>" class="di"><%= power_provider.name %></label>
          </div>
        <% end %>

        <div class="clb"></div>
      </form>

      <main>
        <table class="tac">
          <tr>
            <th></th>

            <% @power_providers.each do |power_provider| %>
              <th class="<%= power_provider.filename %> tac"><%= power_provider.name %></th>
            <% end %>
          </tr>

          <tr>
            <th></th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= image_tag "power_logo_#{power_provider.filename}.jpg" %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Major Shareholder</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.major_shareholder %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Parent Company</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.parent_company %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Major Shareholder/Parent Company Base</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.major_shareholder_base %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Primary Fuel Source</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.primary_fuel_source %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Carbon Emissions</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.carbon_emissions %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Renewable Energy</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.renewable_energy %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>New Renewable Energy Investment</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% if power_provider.new_renewable_energy_investment %>
                  <%= image_tag "green_tick.png" %>
                <% else %>
                  <%= image_tag "red_cross.png" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>No CSG Investment</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% if power_provider.no_csg_investment %>
                  <%= image_tag "green_tick.png" %>
                <% else %>
                  <%= image_tag "red_cross.png" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>GreenPower Available</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% if power_provider.greenpower_available %>
                  <%= image_tag "green_tick.png" %>
                <% else %>
                  <%= image_tag "red_cross.png" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Ombudsman Complaints</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.ombudsman_complaints %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Dual Fuel</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.dual_fuel %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Greenpeace Ranking</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.greenpeace_ranking %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>States of Operation</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% power_provider.states.each do |state| %>
                  <%=  "#{state.short_name} " %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <% if @state %>
            <tr>
              <th>Likely Termination Fee</th>

              <% @power_providers.each do |power_provider| %>
                <td class="<%= power_provider.filename %>">
                  <%= power_provider.termination_fees.find_by(state_id: @state.id).amount %>
                </td>
              <% end %>
            </tr>
          <% end %>

          <tr>
            <th>Ethical Switch Rating</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% power_provider.ethical_switch_rating.to_i.times do %>
                  <%= image_tag "gold_star.png" %>
                <% end %>

                <% (5 - power_provider.ethical_switch_rating).to_i.times do %>
                  <%= image_tag "grey_star.png" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th></th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% if power_provider.partner? %>
                  <%= link_to "Switch Now", new_switch_path(partner_id: power_provider.partner? ? Partner.find_by(name: power_provider.name).id : nil, charity_id: nil), class: "btn btn-primary btn-switch-table" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Extra Things to Note</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %> vat pl15 pr15">
                <div>
                  <%= power_provider.extra_details(power_provider.filename) %>
                </div>
              </td>
            <% end %>
          </tr>
        </table>
      </main>
    </div>

    <div id="power-results-2" class="results-2">
      <table class="mobile-table">
        <thead>
          <tr><?php display_power_table_mobile_headers($powerProvidersArray['tableHeaderArray']); ?></tr>
        </thead>

        <?php if(!empty($powerProvidersArray['powershopArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['powershopArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['diamondArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['diamondArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['originArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['originArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['aglArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['aglArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['energyAustraliaArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['energyAustraliaArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['ergonArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['ergonArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['lumoArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['lumoArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['redArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['redArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['momentumArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['momentumArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['auroraArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['auroraArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['simplyArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['simplyArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['alintaArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['alintaArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['powerdirectArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['powerdirectArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['actewaglArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['actewaglArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['dodoArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['dodoArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['clickArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['clickArray']); ?></tr>

        <?php } ?>

        <?php if(!empty($powerProvidersArray['neighbourhoodArray'][$_SESSION['chosenState']])) { ?>

          <tr><?php display_power_table_mobile($powerProvidersArray['neighbourhoodArray']); ?></tr>

        <?php } ?>
      </table>
    </div>

    <div class="disclaimer mb40 mt40">
      <p>Ethical Switch is comparing providers of goods and services according to publicly available data. We cannot guarantee that we have included all providers, nor can we guarantee this information to be 100% correct, so please do your own research before making a decision to switch. If you believe our information to be incorrect, please contact us and let us know! </p>


      <p>For more information on the criteria table, <%= link_to "click here", criteria_table_info_path, target: "_blank" %></p>
    </div>
  </div>
</div>

app/views/power_providers/_criteria_table_desktop.html.erb
<div id="power_criteria_container" class="dn-sm">
  <% unless action_name == "ethical_power" %>
    <div class="highlight-bg row pt20 pb20 tac text-white">
      <h3>Showing Results for <%= @state ? @state.short_name : "Australia" %>:</h3>
    </div>
  <% end %>
  
  <div class="row grey-bg pt5 pb5">
    <%= form_tag(change_state_path, remote: true) do %>
      <div class="tac" style="line-height:40px;">
        
        <%= @state ? "Change state:" : "Filter by state:" %>
      
        <%= select_tag :state_id, options_from_collection_for_select(State.all, "id", "short_name", selected: @state ? @state.id : nil), prompt: "Select State...", class: "form-control di w200 mb0" %>
      </div>
    <% end %>
    
    <div class="clb"></div>
  </div>

  <div class="criteria_table">
    <div class="tablet-desktop">
      <form id="toggler">
        <div class="cta">
          Compare your providers:
        </div>

        <% @power_providers.each do |power_provider| %>
          <div class="checkboxItem">
            <input type="checkbox" id="<%= power_provider.filename %>" name="<%= power_provider.filename %>" value="<%= power_provider.name %>" class="di" <%= "disabled" if power_provider.partner? %> <%= "checked" if power_provider.prechecked?(@state) %>>
            <label for="<%= power_provider.filename %>" class="di"><%= power_provider.name %></label>
          </div>
        <% end %>

        <div class="clb"></div>
      </form>

      <main>
        <table class="tac">
          <tr>
            <th></th>

            <% @power_providers.each do |power_provider| %>
              <th class="<%= power_provider.filename %> tac"><%= power_provider.name %></th>
            <% end %>
          </tr>

          <tr>
            <th></th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= image_tag "power_logo_#{power_provider.filename}.jpg" %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Major Shareholder</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.major_shareholder %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Parent Company</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.parent_company %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Major Shareholder/Parent Company Base</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.major_shareholder_base %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Primary Fuel Source</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.primary_fuel_source %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Carbon Emissions</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.carbon_emissions %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Renewable Energy</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.renewable_energy %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>New Renewable Energy Investment</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% if power_provider.new_renewable_energy_investment %>
                  <%= image_tag "green_tick.png" %>
                <% else %>
                  <%= image_tag "red_cross.png" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>No CSG Investment</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% if power_provider.no_csg_investment %>
                  <%= image_tag "green_tick.png" %>
                <% else %>
                  <%= image_tag "red_cross.png" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>GreenPower Available</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% if power_provider.greenpower_available %>
                  <%= image_tag "green_tick.png" %>
                <% else %>
                  <%= image_tag "red_cross.png" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Ombudsman Complaints</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.ombudsman_complaints %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Dual Fuel</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.dual_fuel %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Greenpeace Ranking</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <%= power_provider.greenpeace_ranking %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>States of Operation</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% power_provider.states.each do |state| %>
                  <%=  "#{state.short_name} " %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <% if @state %>
            <tr>
              <th>Likely Termination Fee</th>

              <% @power_providers.each do |power_provider| %>
                <td class="<%= power_provider.filename %>">
                  <%= power_provider.termination_fees.find_by(state_id: @state.id).amount %>
                </td>
              <% end %>
            </tr>
          <% end %>

          <tr>
            <th>Ethical Switch Rating</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% power_provider.ethical_switch_rating.to_i.times do %>
                  <%= image_tag "gold_star.png" %>
                <% end %>

                <% (5 - power_provider.ethical_switch_rating).to_i.times do %>
                  <%= image_tag "grey_star.png" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th></th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %>">
                <% if power_provider.partner? %>
                  <%= link_to "Switch Now", new_switch_path(partner_id: power_provider.partner? ? Partner.find_by(name: power_provider.name).id : nil, charity_id: nil), class: "btn btn-primary btn-switch-table" %>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th>Extra Things to Note</th>

            <% @power_providers.each do |power_provider| %>
              <td class="<%= power_provider.filename %> vat pl15 pr15">
                <div>
                  <%= power_provider.extra_details(power_provider.filename) %>
                </div>
              </td>
            <% end %>
          </tr>
        </table>
      </main>
    </div>
  </div>
</div>

app/views/power_providers/_criteria_table_disclaimer.html.erb
<div class="disclaimer mb40 mt40">
  <p>Ethical Switch is comparing providers of goods and services according to publicly available data. We cannot guarantee that we have included all providers, nor can we guarantee this information to be 100% correct, so please do your own research before making a decision to switch. If you believe our information to be incorrect, please contact us and let us know! </p>


  <p>For more information on the criteria table, <%= link_to "click here", criteria_table_info_path, target: "_blank" %></p>
</div>

app/views/power_providers/_criteria_table_mobile.html.erb
<div class="criteria_table_container_mobile">
  <table class="mobile-table">
    <tbody>
      <% @power_providers.each do |power_provider| %>
        <tr>
          <td class="name"><%= power_provider.name %></td>
          <td><%= power_provider.major_shareholder %></td>
          <td><%= power_provider.major_shareholder_base %></td>
          <td><%= power_provider.parent_company %></td>
          <td><%= power_provider.primary_fuel_source %></td>
          <td><%= power_provider.carbon_emissions %></td>
          <td><%= power_provider.renewable_energy %></td>
          <td><%= power_provider.new_renewable_energy_investment %></td>
          <td><%= power_provider.no_csg_investment %></td>
          <td><%= power_provider.greenpower_available %></td>
          <td><%= power_provider.ombudsman_complaints %></td>
          <td><%= power_provider.dual_fuel %></td>
          <td><%= power_provider.greenpeace_ranking %></td>
          
          <td>
            <% power_provider.states.each do |state| %>
              <%= "#{state.short_name} " %>
            <% end %>
          </td>
          
          <% if @state %>
            <td><%= power_provider.termination_fees.find_by(state_id: @state.id).amount %></td>
          <% end %>
          
          <td>
            <% power_provider.ethical_switch_rating.to_i.times do %>
              <%= image_tag "gold_star.png" %>
            <% end %>

            <% (5 - power_provider.ethical_switch_rating).to_i.times do %>
              <%= image_tag "grey_star.png" %>
            <% end %>
          </td>
          
          <% if power_provider.partner? %>
            <td class="button">
              <%= link_to "Switch Now", new_switch_path(partner_id: Partner.find_by(name: power_provider.name).id, charity_id: nil), class: "btn btn-primary btn-switch-table" %>
            </td>
            
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/power_providers/_criteria_tables.html.erb
<%= render 'power_providers/criteria_table_desktop' %>
<%= render 'power_providers/criteria_table_mobile' %>
<%= render 'power_providers/criteria_table_disclaimer' %>

app/views/power_providers/change_state.js.erb
$('#power_criteria_container').replaceWith("<%= j(render 'power_providers/criteria_table_desktop') %>")
$('.criteria_table_container_mobile').replaceWith("<%= j(render 'power_providers/criteria_table_mobile') %>")

app/views/power_providers/index.html.erb
<%= render 'power_providers/criteria_tables' %>